[project]
name = "onnx-vehicle-plate-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colored>=2.3.1",
    "colorlog>=6.9.0",
    "numpy>=2.2.6",
    "onnx>=1.18.0",
    "onnx-graphsurgeon",
    "onnxruntime-gpu[cuda,cudnn]>=1.22.0",
    "opencv-contrib-python>=4.12.0.88",
    "pillow>=11.3.0",
    "polygraphy>=0.49.26",
    "pyyaml>=6.0.2",
    "tensorrt==8.6.1.post1",
]

[tool.uv]
# 配置包索引源
index-url = "https://pypi.org/simple/"
extra-index-url = [
    # NVIDIA NGC PyPI 镜像，用于TensorRT相关包
    "https://pypi.ngc.nvidia.com/simple/",
]

[tool.uv.workspace]
members = ["mcp_vehicle_detection"]
